(MODULES-4653) Install puppetserver on master
puppetlabs/beaker-puppet_install_helper pull request #29
Opened 2017-04-04 15:56 UTC by johnduarte

This commit updates the `run_puppet_install_helper_on` helper method
to install `puppetserver` on the host with a `master` role if one is
present in the beaker hosts array.

2017-04-04 16:22 UTC, DavidS requested changes
`PUPPET_INSTALL_TYPE=agent` is specifically for test suites that do not need a master. use `pe` or `foss` for complete setups, depending on which master version you want to have installed.

2017-04-04 23:36 UTC, johnduarte commented
Thank you @DavidS for clarifying the intention of the `agent` and `foss` install types. The `foss` install type does not currently install a master. I have updated this PR to install a `puppetserver` master on the `master` node if it is defined for the the `foss` install type.

cc @glennsarti

2017-04-06 11:41 UTC, DavidS requested changes

2017-04-06 11:41 UTC, DavidS commented on lib/beaker/puppet_install_helper.rb
> -      end
This should stay in.

2017-04-06 11:41 UTC, DavidS commented on lib/beaker/puppet_install_helper.rb
> +      hosts.each do |host|
:+1: please add a short statement in the README to describe what this is doing.

2017-04-06 16:01 UTC, johnduarte commented
PR updated as per your request @DavidS . Thanks.

2017-04-07 07:47 UTC, DavidS approved these changes
:tada:

2017-04-07 07:47 UTC, merged